/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinica;

/**
 *
 * @author Esteban Lescano <estebanles22 at gmail.com>
 */
public class inicio extends javax.swing.JPanel {

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BtnUrgencia = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton6.setText("jButton6");

        setLayout(null);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo 1.jpg"))); // NOI18N
        jButton1.setText("Con Obra Social");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jButton1);
        jButton1.setBounds(150, 120, 230, 50);

        BtnUrgencia.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BtnUrgencia.setForeground(new java.awt.Color(0, 0, 0));
        BtnUrgencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo 3.jpg"))); // NOI18N
        BtnUrgencia.setText("Urgencias");
        BtnUrgencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnUrgencia.setMaximumSize(new java.awt.Dimension(500, 500));
        BtnUrgencia.setMinimumSize(new java.awt.Dimension(500, 500));
        BtnUrgencia.setPreferredSize(new java.awt.Dimension(500, 500));
        BtnUrgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUrgenciaActionPerformed(evt);
            }
        });
        add(BtnUrgencia);
        BtnUrgencia.setBounds(150, 220, 230, 50);

        jButton5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo 4.jpg"))); // NOI18N
        jButton5.setText("Particular");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jButton5);
        jButton5.setBounds(150, 170, 230, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicio.jpg"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        add(jLabel1);
        jLabel1.setBounds(0, -10, 730, 340);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnUrgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUrgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUrgenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnUrgencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
